production: 
  dirs: 
   - db/backups
  servers: 
    -  name: kradradio backup server
       host: kradradio.com
       port: 22
       user: u35859318
       dir: /kunden/homepages/15/d94665629/htdocs/rawdod3_backups
