development:
  adapter: postgresql
  database: rawdod3_development
  username: postgres
  password: funworld
  host: 127.0.0.1

production:
  adapter: postgresql
  database: rawdod3_production
  username: postgres
  password: funworld
  host: 127.0.0.1
