# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "comments", :force => true do |t|
    t.column "user_id",    :integer
    t.column "post_id",    :integer
    t.column "body",       :text
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "images", :force => true do |t|
    t.column "post_id",  :integer
    t.column "position", :integer
    t.column "filename", :string
    t.column "body",     :text
  end

  create_table "messages", :force => true do |t|
    t.column "user_id",    :integer
    t.column "to_user_id", :integer
    t.column "body",       :text
  end

  create_table "posts", :force => true do |t|
    t.column "user_id",      :integer
    t.column "title",        :string
    t.column "body",         :text
    t.column "url",          :string
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
    t.column "commented_on", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",               :string
    t.column "password",            :string
    t.column "seen_on",             :datetime
    t.column "authorization_token", :string
  end

end
